/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Hfhfhggh as PrismaHfhfhggh } from "@prisma/client";

export class HfhfhgghServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.HfhfhgghCountArgs, "select">): Promise<number> {
    return this.prisma.hfhfhggh.count(args);
  }

  async hfhfhgghs(
    args: Prisma.HfhfhgghFindManyArgs
  ): Promise<PrismaHfhfhggh[]> {
    return this.prisma.hfhfhggh.findMany(args);
  }
  async hfhfhggh(
    args: Prisma.HfhfhgghFindUniqueArgs
  ): Promise<PrismaHfhfhggh | null> {
    return this.prisma.hfhfhggh.findUnique(args);
  }
  async createHfhfhggh(
    args: Prisma.HfhfhgghCreateArgs
  ): Promise<PrismaHfhfhggh> {
    return this.prisma.hfhfhggh.create(args);
  }
  async updateHfhfhggh(
    args: Prisma.HfhfhgghUpdateArgs
  ): Promise<PrismaHfhfhggh> {
    return this.prisma.hfhfhggh.update(args);
  }
  async deleteHfhfhggh(
    args: Prisma.HfhfhgghDeleteArgs
  ): Promise<PrismaHfhfhggh> {
    return this.prisma.hfhfhggh.delete(args);
  }
}
