/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Hfhfhggh } from "./Hfhfhggh";
import { HfhfhgghCountArgs } from "./HfhfhgghCountArgs";
import { HfhfhgghFindManyArgs } from "./HfhfhgghFindManyArgs";
import { HfhfhgghFindUniqueArgs } from "./HfhfhgghFindUniqueArgs";
import { CreateHfhfhgghArgs } from "./CreateHfhfhgghArgs";
import { UpdateHfhfhgghArgs } from "./UpdateHfhfhgghArgs";
import { DeleteHfhfhgghArgs } from "./DeleteHfhfhgghArgs";
import { HfhfhgghService } from "../hfhfhggh.service";
@graphql.Resolver(() => Hfhfhggh)
export class HfhfhgghResolverBase {
  constructor(protected readonly service: HfhfhgghService) {}

  async _hfhfhgghsMeta(
    @graphql.Args() args: HfhfhgghCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Hfhfhggh])
  async hfhfhgghs(
    @graphql.Args() args: HfhfhgghFindManyArgs
  ): Promise<Hfhfhggh[]> {
    return this.service.hfhfhgghs(args);
  }

  @graphql.Query(() => Hfhfhggh, { nullable: true })
  async hfhfhggh(
    @graphql.Args() args: HfhfhgghFindUniqueArgs
  ): Promise<Hfhfhggh | null> {
    const result = await this.service.hfhfhggh(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Hfhfhggh)
  async createHfhfhggh(
    @graphql.Args() args: CreateHfhfhgghArgs
  ): Promise<Hfhfhggh> {
    return await this.service.createHfhfhggh({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Hfhfhggh)
  async updateHfhfhggh(
    @graphql.Args() args: UpdateHfhfhgghArgs
  ): Promise<Hfhfhggh | null> {
    try {
      return await this.service.updateHfhfhggh({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Hfhfhggh)
  async deleteHfhfhggh(
    @graphql.Args() args: DeleteHfhfhgghArgs
  ): Promise<Hfhfhggh | null> {
    try {
      return await this.service.deleteHfhfhggh(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
