/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { HfhfhgghService } from "../hfhfhggh.service";
import { HfhfhgghCreateInput } from "./HfhfhgghCreateInput";
import { Hfhfhggh } from "./Hfhfhggh";
import { HfhfhgghFindManyArgs } from "./HfhfhgghFindManyArgs";
import { HfhfhgghWhereUniqueInput } from "./HfhfhgghWhereUniqueInput";
import { HfhfhgghUpdateInput } from "./HfhfhgghUpdateInput";

export class HfhfhgghControllerBase {
  constructor(protected readonly service: HfhfhgghService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Hfhfhggh })
  async createHfhfhggh(
    @common.Body() data: HfhfhgghCreateInput
  ): Promise<Hfhfhggh> {
    return await this.service.createHfhfhggh({
      data: data,
      select: {
        createdAt: true,
        fhryry: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Hfhfhggh] })
  @ApiNestedQuery(HfhfhgghFindManyArgs)
  async hfhfhgghs(@common.Req() request: Request): Promise<Hfhfhggh[]> {
    const args = plainToClass(HfhfhgghFindManyArgs, request.query);
    return this.service.hfhfhgghs({
      ...args,
      select: {
        createdAt: true,
        fhryry: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Hfhfhggh })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async hfhfhggh(
    @common.Param() params: HfhfhgghWhereUniqueInput
  ): Promise<Hfhfhggh | null> {
    const result = await this.service.hfhfhggh({
      where: params,
      select: {
        createdAt: true,
        fhryry: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Hfhfhggh })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateHfhfhggh(
    @common.Param() params: HfhfhgghWhereUniqueInput,
    @common.Body() data: HfhfhgghUpdateInput
  ): Promise<Hfhfhggh | null> {
    try {
      return await this.service.updateHfhfhggh({
        where: params,
        data: data,
        select: {
          createdAt: true,
          fhryry: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Hfhfhggh })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteHfhfhggh(
    @common.Param() params: HfhfhgghWhereUniqueInput
  ): Promise<Hfhfhggh | null> {
    try {
      return await this.service.deleteHfhfhggh({
        where: params,
        select: {
          createdAt: true,
          fhryry: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
